spring.application.name=CustomSystemBack
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/customSystem
spring.datasource.username=root
spring.datasource.password=guillermo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


#INICIO DE SESION CON GOOGLE
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=


